# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

env:
  DOCUMENTER_DEBUG: true
  
os:
  - linux
  - osx
  
julia:
  - 1.2
  - 1.3
  - 1.4
  - nightly
  
matrix:
  allow_failures:
    - julia: 1.4, nightly
    - os: osx
    
env:
    global:
    - PYTHON=""
#    matrix:
#    - MPMATH=true
    
notifications:
  email: true
  
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build("PyCall"); Pkg.develop("Symata"); Pkg.test("NumericalMethodsforEngineers"; coverage=true)'
  
#before_install:
#  - julia -e 'using Pkg; Pkg.build("PyCall"); Pkg.develop("Symata")'
  
after_success:
  #
  # Documentation
  #
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("NumericalMethodsforEngineers")); include(joinpath("docs", "make.jl"))'
  #
  # Coverage
  #
  # push coverage results to Coveralls
  #
  - julia -e 'cd(Pkg.dir("NumericalMethodsforEngineers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  #
  # push coverage results to Codecov
  #
  - julia -e 'cd(Pkg.dir("NumericalMethodsforEngineers")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'