name = "NumericalMethodsforEngineers"
uuid = "00e1d38a-71a9-5665-8612-32ae585a75a3"
authors = ["Rob J Goedman <goedman@mac.com>"]
version = "1.2.3"

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BandedMatrices = "0.15, 0.16"
Calculus = "0.5"
DataFrames = "0.22, 1.0"
FillArrays = "0.10, 0.11"
GR = "0.53, 0.54, 0.55, 0.57"
IterativeSolvers = "0.8, 0.9"
PyCall = "1.91"
QuadGK = "2.1"
Reexport = "0.2, 1.0"
julia = "1"
